# ========================================
# Dependabot Configuration
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# ========================================
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: auto
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: scope
    reviewers:
      - Ven0m0
    labels:
      - dependencies
      - github-actions
      - automated
    groups:
      github-actions-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
